services:
  - type: web
    name: ai-job-tracker-api
    runtime: node
    buildCommand: npm install && npx prisma generate && npx nest build
    startCommand: node dist/main
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: GROQ_API_KEY
        sync: false
      - key: FRONTEND_URL
        sync: false
